###################################################
# pum
###################################################

[[plugins]]
repo = 'Shougo/pum.vim'
on_source = 'denops.vim'


###################################################
# ddc
###################################################

[[plugins]]
repo = 'Shougo/ddc.vim'
on_source = 'denops.vim'
hook_source = 'source $VIM_DEIN/lazy/config/ddc.vim'

# ui
[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = 'ddc.vim'

# matcher
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

# sorter
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

# converter
[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
on_source = 'ddc.vim'
