###################################################
# ddu
###################################################

[[plugins]]
repo = 'Shougo/ddu.vim'
on_source = 'denops.vim'

###### ui(filer) ######
[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
depends = ['ddu.vim']
hook_source = 'source $XDG_CONFIG_HOME/nvim/dein/lazy/config/ddu-ui-filer.vim'

###### ui(fuzzy finder) ######
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
depends = ['ddu.vim']
hook_source = 'source $XDG_CONFIG_HOME/nvim/dein/lazy/config/ddu-ui-ff.vim'

###### matcher ######
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'
depends = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_files'
on_source = 'ddu.vim'
depends = ['ddu.vim']

###### kind ######
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'
depends = ['ddu.vim']

###### source ######
[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'
depends = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu-kind-file'
depends = ['ddu.vim']

###### column ######
[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'
depends = ['ddu.vim']

###### converter ######
repo = 'uga-rosa/ddu-filter-converter_devicon'
on_source = 'ddu.vim'
depends = ['ddu.vim']
