###################################################
# defx
###################################################

[[plugins]]
repo = 'Shougo/defx.nvim'
if = '!exists("g:vscode")'
on_event = 'BufEnter'
hook_source = 'source $VIM_DEIN/lazy/config/defx.vim'

[[plugins]]
repo = 'kristijanhusak/defx-git'
on_source = 'defx.nvim'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
on_source = 'defx.nvim'
