###################################################
# denops
###################################################

[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'BufEnter'
# if = '!exists("g:vscode")'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'denops.vim'

[[plugins]]
repo = 'matsui54/denops-signature_help'
on_source = 'denops.vim'
hook_source = 'source $VIM_DEIN/lazy/config/denops.vim'
