###################################################
# denops
###################################################
# なぜかここに入れないと依存関係エラーになる
[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'BufEnter'
if = '!exists("g:vscode")'