###################################################
# nvim-lsp
###################################################

[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_source = 'ddc-source-lsp-setup'
if = '!exists("g:vscode")'


###################################################
# mason
###################################################

[[plugins]]
repo = 'williamboman/mason.nvim'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
hook_source = 'source $XDG_CONFIG_HOME/nvim/dein/lazy/config/mason-lspconfig.lua'
on_source = 'mason.nvim'

