###################################################
# mason
###################################################

[[plugins]]
repo = 'williamboman/mason.nvim'
if = '!exists("g:vscode")'
on_event = 'BufEnter'
hook_source = 'source $VIM_DEIN/lazy/config/mason.lua'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'nvim-lspconfig'


###################################################
# nvim-lsp
###################################################

[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_source = 'mason.nvim'
hook_source = 'source $VIM_DEIN/lazy/config/nvim-lspconfig.lua'


###################################################
# Scala
###################################################

[[plugins]]
repo = 'scalameta/nvim-metals'
if = '!exists("g:vscode")'
on_ft = 'scala'
hook_source = 'source $VIM_DEIN/lazy/config/nvim-metals.vim'


###################################################
# aerial
###################################################

[[plugins]]
repo = 'stevearc/aerial.nvim'
on_source = 'nvim-lspconfig'


###################################################
# Navigation bar
###################################################

[[plugins]]
repo = 'SmiteshP/nvim-navic'
on_source = 'nvim-lspconfig'
hook_source = 'source $VIM_DEIN/lazy/config/nvim-navic.lua'

###################################################
# Error List
###################################################
[[plugins]]
repo = 'folke/trouble.nvim'
if = '!exists("g:vscode")'
depends = ['nvim-web-devicons']
on_event = 'BufEnter'
hook_source = 'source $VIM_DEIN/lazy/config/trouble.vim'
