###################################################
# Scala Settings
###################################################

[[plugins]]
repo = 'scalameta/nvim-metals'
hook_source = 'source $XDG_CONFIG_HOME/nvim/dein/lazy/config/nvim-metals.vim'
on_ft = 'scala'
if = '!exists("g:vscode")'
