###################################################
# defx
###################################################

[[plugins]]
repo = 'Shougo/defx.nvim'
if = '!exists("g:vscode")'
on_event = 'BufEnter'
hook_source = 'source ~/AppData/Local/nvim/dein/plugins/config_defx.vim'

[[plugins]]
repo = 'kristijanhusak/defx-git'
on_source = 'defx.nvim'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
on_source = 'defx.nvim'


###################################################
# denops
###################################################

[[plugins]]
repo = 'vim-denops/denops.vim'
if = '!exists("g:vscode")'
on_event = 'BufEnter'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'denops.vim'

[[plugins]]
repo = 'matsui54/denops-signature_help'
on_source = 'denops.vim'
hook_source = 'source ~/AppData/Local/nvim/dein/plugins/config_denops.vim'

###################################################
# ddu
###################################################

[[plugins]]
repo = 'Shougo/ddu.vim'
on_source = 'denops.vim'
hook_source = 'source ~/AppData/Local/nvim/dein/plugins/config_ddu.vim'

###### ui(filer) ######
[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
depends = ['ddu.vim']

###### ui(fuzzy finder) ######
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
depends = ['ddu.vim']

###### matcher ######
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'
depends = ['ddu.vim']

###### kind ######
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'
depends = ['ddu.vim']

###### source ######
[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'
depends = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu-kind-file'
depends = ['ddu.vim']

###### column ######
[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'
depends = ['ddu.vim']


###################################################
# pum
###################################################

[[plugins]]
repo = 'Shougo/pum.vim'
on_source = 'denops.vim'
hook_source = 'source ~/AppData/Local/nvim/dein/plugins/config_pum.vim'


###################################################
# ddc
###################################################

[[plugins]]
repo = 'Shougo/ddc.vim'
on_source = 'denops.vim'
hook_source = 'source ~/AppData/Local/nvim/dein/plugins/config_ddc.vim'

# matcher
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

# sorter
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

# converter
[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
on_source = 'ddc.vim'

###################################################
# nvim-lsp
###################################################

[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_source = 'ddc.vim'
hook_source = 'source ~/AppData/Local/nvim/dein/plugins/config_nvim-lspconfig.lua'


###################################################
# Scala
###################################################

[[plugins]]
repo = 'scalameta/nvim-metals'
if = '!exists("g:vscode")'
on_ft = 'scala'
hook_source = 'source ~/AppData/Local/nvim/dein/plugins/config_nvim-metals.vim'
