###################################################
# IDE Support
###################################################
# Startup Window
[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = 'source $VIM_DEIN/config/startify.vim'
#if = 'exists("g:goneovim")'

# Status Line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source $VIM_DEIN/config/lightline.vim'
if = '!exists("g:vscode")'

# Buffer Line
[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
if = '!exists("g:vscode")'

# Open/Close Terminal by command
# [[plugins]]
# repo = 'akinsho/toggleterm.nvim'
# if = '!exists("g:vscode")'
# hook_add = 'source $VIM_DEIN/config/toggleterm.vim'


###################################################
# Utility
###################################################
[[plugins]]
repo = 'airblade/vim-gitgutter' 
hook_add = 'source $VIM_DEIN/config/gitgutter.vim'
if = '!exists("g:vscode")'

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = 'source $VIM_DEIN/config/vim-rooter.vim'
if = '!exists("g:vscode")'

[[plugins]]
repo = 'famiu/bufdelete.nvim'
hook_add = 'source $VIM_DEIN/config/bufdelete.vim'
if = '!exists("g:vscode")'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-repeat'


###################################################
# Move Support
###################################################
[[plugins]]
repo = 'bkad/CamelCaseMotion'
hook_add = 'source $VIM_DEIN/config/CamelCaseMotion.vim'
if = '!exists("g:vscode")'

[[plugins]]
repo = 'haya14busa/vim-edgemotion'
hook_add = 'source $VIM_DEIN/config/vim-edgemotion.vim'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'unblevable/quick-scope'


###################################################
# Input Support
###################################################
[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'


###################################################
# Search Support
###################################################
[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'
hook_add = 'source $VIM_DEIN/config/hlslens.lua'

[[plugins]]
repo = 't9md/vim-quickhl'

###################################################
# Replacement Support
###################################################
[[plugins]]
repo = 'markonm/traces.vim'
if = '!exists("g:vscode")'


###################################################
# Visualization
###################################################

# Indent Support
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'source $VIM_DEIN/config/indentLine.vim'
if = '!(exists("g:vscode") || exists("g:goneovim"))'

# TODO Coloring
[[plugins]]
repo = 'folke/todo-comments.nvim'
if = '!exists("g:vscode")'