###################################################
# Utility
###################################################

# 行の横にgitの差分表示を行う
[[plugins]]
repo = 'airblade/vim-gitgutter' 
hook_add = 'source $XDG_CONFIG_HOME/nvim/dein/config/gitgutter.vim'
if = '!exists("g:vscode")'

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = 'source $XDG_CONFIG_HOME/nvim/dein/config/vim-rooter.vim'
if = '!exists("g:vscode")'

[[plugins]]
repo = 'famiu/bufdelete.nvim'
hook_add = 'source $XDG_CONFIG_HOME/nvim/dein/config/bufdelete.vim'
if = '!exists("g:vscode")'

# Gitの操作をvimコマンドで行う
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-repeat'

# Startup Window
[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = 'source $XDG_CONFIG_HOME/nvim/dein/config/startify.vim'
if = '!exists("g:vscode")'


###################################################
# Move Support
###################################################
[[plugins]]
repo = 'bkad/CamelCaseMotion'
hook_add = 'source $XDG_CONFIG_HOME/nvim/dein/config/CamelCaseMotion.vim'
if = '!exists("g:vscode")'

[[plugins]]
repo = 'haya14busa/vim-edgemotion'
hook_add = 'source $XDG_CONFIG_HOME/nvim/dein/config/vim-edgemotion.vim'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'unblevable/quick-scope'


###################################################
# Input Support
###################################################
[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'


###################################################
# Search Support
###################################################
[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'
hook_add = 'source $XDG_CONFIG_HOME/nvim/dein/config/hlslens.lua'

[[plugins]]
repo = 't9md/vim-quickhl'


###################################################
# Replacement Support
###################################################
[[plugins]]
repo = 'markonm/traces.vim'
if = '!exists("g:vscode")'


###################################################
# Visualization
###################################################

# Indent Support
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'source $XDG_CONFIG_HOME/nvim/dein/config/indentLine.vim'
if = '!(exists("g:vscode") || exists("g:goneovim"))'

# TODO Coloring
[[plugins]]
repo = 'folke/todo-comments.nvim'
if = '!exists("g:vscode")'